language: common-lisp

env:
  matrix:
#    - LISP=abcl
    - LISP=allegro
    - LISP=sbcl
    - LISP=sbcl32
    - LISP=ccl
    - LISP=ccl32
    - LISP=clisp
    - LISP=clisp32
#    - LISP=cmucl
    - LISP=ecl

#matrix:
#  allow_failures:
    # CIM not available for CMUCL
#    - env: LISP=cmucl

install:
  - if [ -x ./install.sh ] && head -2 ./install.sh | grep '^# cl-travis' > /dev/null;
    then
      ./install.sh;
    else
      curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | sh;
    fi

  - git clone https://github.com/fukamachi/prove

script:
  - cl -e '(in-package :cl-user)'
       -e "(ql:quickload '(prove cl21))"
       -e '(setf prove:*debug-on-error* t)'
       -e '(setf *debugger-hook*
                 (lambda (c h)
                   (declare (ignore c h))
                   (uiop:quit -1)))'
       -e '(let ((test-results (prove:run :cl21-test)))
             (or test-results
                 (uiop:quit -1)))'
